import { StudentProfile, GenieResponse } from './types';

export const DEMO_STUDENT: StudentProfile = {
  name: 'Arjun Mehta',
  year: 2,
  department: 'CSE',
  careerGoal: 'AI Engineer',
  availableHoursPerWeek: 15,
  gpa: 8.5,
  currentSkills: [
    { name: 'Java', level: 3 },
    { name: 'SQL', level: 3 },
    { name: 'Git', level: 2 },
    { name: 'Linux', level: 2 },
    { name: 'Problem Solving', level: 2 },
  ],
};

export const GOLDEN_PATH_RESPONSE: GenieResponse = {
  query: "I'm Arjun Mehta, a 2nd-year CSE student. I know Java and SQL. I want to become an AI Engineer. What campus opportunities should I pursue and in what order?",
  explanation: "Arjun, based on your profile as a 2nd-year CSE student with Java and SQL background, you need to build 5 key skill gaps: Python (L3), Machine Learning (L3), TensorFlow (L2), Natural Language Processing (L2), and Model Deployment (L2). Given your 15 hrs/week budget, here is your 4-phase sequential roadmap:",
  placementTarget: {
    role: 'AI Engineer',
    company: 'TechCorp India',
    packageLpa: 18.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'Campus Backend API Project',
      type: 'Project',
      whyFits: 'Uses your existing Java & SQL strengths to teach Python & REST API design.',
      prerequisites: 'Java (Level 2), SQL (Level 2)',
      weeklyHours: 6,
      unlocks: 'Python (Level 2), REST APIs (Level 3), Docker (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 2,
      title: 'AI/ML Club (Meets Wednesdays)',
      type: 'Club',
      whyFits: 'Introduces core Machine Learning, Statistics & Scikit-Learn with peer mentorship.',
      prerequisites: 'Python (Level 1)',
      weeklyHours: 4,
      unlocks: 'Machine Learning (Level 2), Statistics (Level 2), Scikit-Learn (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 3,
      title: 'Applied AI Workshop (Oct 15)',
      type: 'Event',
      whyFits: 'Hands-on intensive workshop covering TensorFlow neural networks & model deployment.',
      prerequisites: 'Python (Level 2), ML (Level 1)',
      weeklyHours: 4,
      unlocks: 'TensorFlow (Level 3), Model Deployment (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 4,
      title: 'NLP for Indian Languages Research',
      type: 'Research',
      whyFits: 'Under Dr. Rajesh Kumar (CSE). Deepens NLP & Transformers on real-world datasets.',
      prerequisites: 'Python (Level 3), ML (Level 2)',
      weeklyHours: 8,
      unlocks: 'Natural Language Processing (Level 4), Deep Learning (Level 3), Research Methods (Level 3)',
      noteColor: 'mint',
    },
    {
      stepNumber: 5,
      title: 'DataHack 2026 Hackathon (Nov 15)',
      type: 'Hackathon',
      whyFits: '48-hour competitive hackathon to prove end-to-end ML delivery and teamwork.',
      prerequisites: 'Python (Level 2), ML (Level 2)',
      weeklyHours: 3,
      unlocks: 'End-to-End ML (Level 3), Teamwork (Level 3), Presentation (Level 3)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 6,
      title: 'TechCorp India AI Engineer Placement',
      type: 'Placement',
      whyFits: 'Target placement role at ₹18 LPA. All 5 skill requirements now 100% satisfied!',
      prerequisites: 'Python (L3), ML (L3), TensorFlow (L2), NLP (L2), Model Deployment (L2)',
      weeklyHours: 0,
      unlocks: 'Full-time AI Engineer Job Offer (₹18 LPA)',
      noteColor: 'mint',
    },
  ],
};

export const WHATIF_5HRS_RESPONSE: GenieResponse = {
  query: 'What if Arjun only has 5 hours per week available?',
  isWhatIf: true,
  whatIfConstraint: 'Strict time budget <= 5 hours/week',
  explanation: 'Genie re-planned the path across the graph: dropped the 8-hour research project, replaced it with lightweight seminars & a 4-hour dashboard project, and extended the timeline while keeping total weekly commitment under 5 hours!',
  placementTarget: {
    role: 'AI Engineer',
    company: 'TechCorp India',
    packageLpa: 18.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'AI/ML Club (Meets Wednesdays)',
      type: 'Club',
      whyFits: 'Fits right inside your 5-hour budget (4 hrs/wk). Covers ML & Python fundamentals.',
      prerequisites: 'Python (Level 1)',
      weeklyHours: 4,
      unlocks: 'Machine Learning (Level 2), Statistics (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 2,
      title: 'Interactive Data Dashboard Project',
      type: 'Project',
      whyFits: 'Lightweight project (4 hrs/wk) replacing the 6-hr backend project. Uses SQL & Python.',
      prerequisites: 'Python (Level 2), SQL (Level 1)',
      weeklyHours: 4,
      unlocks: 'Data Visualization (Level 3), Data Analysis (Level 2)',
      noteColor: 'yellow',
      isModified: true,
      originalTitle: 'Campus Backend API Project (6 hrs/wk — Too Heavy)',
    },
    {
      stepNumber: 3,
      title: 'Applied AI Workshop (Oct 15)',
      type: 'Event',
      whyFits: 'Short weekend workshop (4 hrs/wk equivalent). Hands-on TensorFlow practice.',
      prerequisites: 'Python (Level 2), ML (Level 1)',
      weeklyHours: 4,
      unlocks: 'TensorFlow (Level 3), Model Deployment (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 4,
      title: 'NLP with Transformers Seminar (Nov 10)',
      type: 'Event',
      whyFits: 'Replaces the 8-hour/week research project with a targeted 3-hour seminar series.',
      prerequisites: 'Python (Level 2), ML (Level 2)',
      weeklyHours: 3,
      unlocks: 'Natural Language Processing (Level 3)',
      noteColor: 'mint',
      isModified: true,
      originalTitle: 'NLP for Indian Languages Research (8 hrs/wk — Deferred)',
    },
    {
      stepNumber: 5,
      title: 'Campus Chatbot Project',
      type: 'Project',
      whyFits: '5 hrs/week max commitment. Builds practical NLP chatbot for campus FAQ.',
      prerequisites: 'Python (Level 2), SQL (Level 1)',
      weeklyHours: 5,
      unlocks: 'NLP (Level 2), REST (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 6,
      title: 'TechCorp India AI Engineer Placement',
      type: 'Placement',
      whyFits: 'Same placement target reached under a lighter, steady 5-hour weekly pace!',
      prerequisites: 'Python (L3), ML (L3), TensorFlow (L2), NLP (L2)',
      weeklyHours: 0,
      unlocks: 'Full-time AI Engineer Job Offer (₹18 LPA)',
      noteColor: 'mint',
    },
  ],
};
