import { StudentProfile, GenieResponse } from './types';

export const DEMO_STUDENT: StudentProfile = {
  name: 'Arjun Mehta',
  year: 2,
  department: 'CSE',
  careerGoal: 'AI Engineer',
  availableHoursPerWeek: 15,
  gpa: 8.5,
  currentSkills: [
    { name: 'Java', level: 3 },
    { name: 'SQL', level: 3 },
    { name: 'Git', level: 2 },
    { name: 'Linux', level: 2 },
    { name: 'Problem Solving', level: 2 },
  ],
};

// 1. Golden Path: Arjun Mehta → AI Engineer
export const GOLDEN_PATH_RESPONSE: GenieResponse = {
  query: "I'm Arjun Mehta, a 2nd-year CSE student. I know Java and SQL. I want to become an AI Engineer. What campus opportunities should I pursue and in what order?",
  explanation: "Arjun, based on your profile as a 2nd-year CSE student with Java and SQL background, you need to build 5 key skill gaps: Python (L3), Machine Learning (L3), TensorFlow (L2), Natural Language Processing (L2), and Model Deployment (L2). Given your 15 hrs/week budget, here is your 4-phase sequential roadmap:",
  placementTarget: {
    role: 'AI Engineer',
    company: 'TechCorp India',
    packageLpa: 18.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'Campus Backend API Project',
      type: 'Project',
      whyFits: 'Uses your existing Java & SQL strengths to teach Python & REST API design.',
      prerequisites: 'Java (Level 2), SQL (Level 2)',
      weeklyHours: 6,
      unlocks: 'Python (Level 2), REST APIs (Level 3), Docker (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 2,
      title: 'AI/ML Club (Meets Wednesdays)',
      type: 'Club',
      whyFits: 'Introduces core Machine Learning, Statistics & Scikit-Learn with peer mentorship.',
      prerequisites: 'Python (Level 1)',
      weeklyHours: 4,
      unlocks: 'Machine Learning (Level 2), Statistics (Level 2), Scikit-Learn (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 3,
      title: 'Applied AI Workshop (Oct 15)',
      type: 'Event',
      whyFits: 'Hands-on intensive workshop covering TensorFlow neural networks & model deployment.',
      prerequisites: 'Python (Level 2), ML (Level 1)',
      weeklyHours: 4,
      unlocks: 'TensorFlow (Level 3), Model Deployment (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 4,
      title: 'NLP for Indian Languages Research',
      type: 'Research',
      whyFits: 'Under Dr. Rajesh Kumar (CSE). Deepens NLP & Transformers on real-world datasets.',
      prerequisites: 'Python (Level 3), ML (Level 2)',
      weeklyHours: 8,
      unlocks: 'Natural Language Processing (Level 4), Deep Learning (Level 3), Research Methods (Level 3)',
      noteColor: 'mint',
    },
    {
      stepNumber: 5,
      title: 'DataHack 2026 Hackathon (Nov 15)',
      type: 'Hackathon',
      whyFits: '48-hour competitive hackathon to prove end-to-end ML delivery and teamwork.',
      prerequisites: 'Python (Level 2), ML (Level 2)',
      weeklyHours: 3,
      unlocks: 'End-to-End ML (Level 3), Teamwork (Level 3), Presentation (Level 3)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 6,
      title: 'TechCorp India AI Engineer Placement',
      type: 'Placement',
      whyFits: 'Target placement role at ₹18 LPA. All 5 skill requirements now 100% satisfied!',
      prerequisites: 'Python (L3), ML (L3), TensorFlow (L2), NLP (L2), Model Deployment (L2)',
      weeklyHours: 0,
      unlocks: 'Full-time AI Engineer Job Offer (₹18 LPA)',
      noteColor: 'mint',
    },
  ],
};

// 2. Priya Sharma → Product Manager Path
export const PRIYA_PM_RESPONSE: GenieResponse = {
  query: "Priya Sharma is a 2nd-year CSE student who knows HTML/CSS and JavaScript. She wants to become a Product Manager. What's her best opportunity path?",
  explanation: "Priya, based on your profile as a 2nd-year CSE student with HTML/CSS and JavaScript skills, your path to Product Management requires: Product Management (L3), UI/UX Design (L3), Data Analysis (L2), Public Speaking (L2), and Agile/Scrum (L2). Here is your tailored product roadmap:",
  placementTarget: {
    role: 'Associate Product Manager',
    company: 'ProductHive',
    packageLpa: 14.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'Design Thinking Lab',
      type: 'Club',
      whyFits: 'Teaches user research, wireframing, UI/UX design, and design sprints.',
      prerequisites: 'None (Beginner friendly)',
      weeklyHours: 3,
      unlocks: 'UI/UX Design (Level 3), Product Management (Level 2), Presentation (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 2,
      title: 'UX Design Sprint (Oct 10)',
      type: 'Event',
      whyFits: '2-day intensive design thinking and interactive prototyping workshop.',
      prerequisites: 'HTML/CSS (Level 2)',
      weeklyHours: 4,
      unlocks: 'UI/UX Design (Level 3), Product Management (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 3,
      title: 'Entrepreneurship Cell (Meets Tuesdays)',
      type: 'Club',
      whyFits: 'Learn product market fit, business model canvas, pitching, and agile management.',
      prerequisites: 'None',
      weeklyHours: 3,
      unlocks: 'Product Management (Level 3), Public Speaking (Level 3), Leadership (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 4,
      title: 'Startup Weekend Hackathon (Nov 8)',
      type: 'Hackathon',
      whyFits: '54-hour hackathon to take a product idea from zero to prototype & investor pitch.',
      prerequisites: 'HTML/CSS (Level 2), JS (Level 2)',
      weeklyHours: 4,
      unlocks: 'Product Management (Level 3), Pitching (Level 3), Teamwork (Level 3)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 5,
      title: 'AI for Product Analytics Research',
      type: 'Research',
      whyFits: 'Under Dr. Rekha Menon (MBA Dept). Analyze user behavior & product metrics with ML.',
      prerequisites: 'Python (Level 2), Data Analysis (Level 2)',
      weeklyHours: 5,
      unlocks: 'Product Management (Level 3), Machine Learning (Level 2), Data Visualization (Level 3)',
      noteColor: 'mint',
    },
    {
      stepNumber: 6,
      title: 'ProductHive Associate Product Manager Placement',
      type: 'Placement',
      whyFits: 'APM role at ₹14 LPA. Product management, analytics & design skills 100% matched!',
      prerequisites: 'PM (L3), Data Analysis (L2), UI/UX (L2), Speaking (L2)',
      weeklyHours: 0,
      unlocks: 'Full-time Associate Product Manager Offer (₹14 LPA)',
      noteColor: 'mint',
    },
  ],
};

// 3. Data Scientist Path (Rahul / General Data Science)
export const DATA_SCIENTIST_RESPONSE: GenieResponse = {
  query: "What if Arjun wanted to become a Data Scientist instead of an AI Engineer?",
  explanation: "Switching career target to Data Scientist (DataMinds Analytics • ₹15 LPA). This target prioritizes: Statistics (L3), Data Analysis (L3), Python (L3), Machine Learning (L2), and Data Visualization (L2). Here is your re-planned Data Science path:",
  placementTarget: {
    role: 'Data Scientist',
    company: 'DataMinds Analytics',
    packageLpa: 15.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'Data Analytics Club (Meets Thursdays)',
      type: 'Club',
      whyFits: 'Uses your existing SQL skills to build statistical analysis & visualization in Python.',
      prerequisites: 'SQL (Level 1)',
      weeklyHours: 3,
      unlocks: 'Data Analysis (Level 3), Data Visualization (Level 3), Python (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 2,
      title: 'Python for Data Science Bootcamp (Sep 20)',
      type: 'Event',
      whyFits: '3-day intensive bootcamp covering Pandas, NumPy, Scikit-Learn & Matplotlib.',
      prerequisites: 'None',
      weeklyHours: 8,
      unlocks: 'Python (Level 3), Data Analysis (Level 2), Scikit-Learn (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 3,
      title: 'Predictive Student Outcomes Research',
      type: 'Research',
      whyFits: 'Under Dr. Priya Nair (MATH Dept). Build statistical models for academic analytics.',
      prerequisites: 'Python (Level 2), Statistics (Level 3)',
      weeklyHours: 6,
      unlocks: 'Machine Learning (Level 3), Scikit-Learn (Level 3), Research Methods (Level 3)',
      noteColor: 'mint',
    },
    {
      stepNumber: 4,
      title: 'Data Engineering Challenge (Nov 30)',
      type: 'Hackathon',
      whyFits: '36-hour challenge building production data pipelines & analytical dashboards.',
      prerequisites: 'Python (Level 2), SQL (Level 2)',
      weeklyHours: 4,
      unlocks: 'Data Engineering (Level 3), ETL (Level 2), Databricks (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 5,
      title: 'DataMinds Analytics Data Scientist Placement',
      type: 'Placement',
      whyFits: 'Data Scientist role at ₹15 LPA. All 5 statistical & analytical skill gaps satisfied!',
      prerequisites: 'Python (L3), ML (L2), Statistics (L3), Data Analysis (L3)',
      weeklyHours: 0,
      unlocks: 'Full-time Data Scientist Job Offer (₹15 LPA)',
      noteColor: 'mint',
    },
  ],
};

// 4. What-If 5 Hours Constraint Path
export const WHATIF_5HRS_RESPONSE: GenieResponse = {
  query: 'What if Arjun only has 5 hours per week available?',
  isWhatIf: true,
  whatIfConstraint: 'Strict time budget <= 5 hours/week',
  explanation: 'Genie re-planned the path across the graph: dropped the 8-hour research project, replaced it with lightweight seminars & a 4-hour dashboard project, and extended the timeline while keeping total weekly commitment under 5 hours!',
  placementTarget: {
    role: 'AI Engineer',
    company: 'TechCorp India',
    packageLpa: 18.0,
  },
  steps: [
    {
      stepNumber: 1,
      title: 'AI/ML Club (Meets Wednesdays)',
      type: 'Club',
      whyFits: 'Fits right inside your 5-hour budget (4 hrs/wk). Covers ML & Python fundamentals.',
      prerequisites: 'Python (Level 1)',
      weeklyHours: 4,
      unlocks: 'Machine Learning (Level 2), Statistics (Level 2)',
      noteColor: 'cyan',
    },
    {
      stepNumber: 2,
      title: 'Interactive Data Dashboard Project',
      type: 'Project',
      whyFits: 'Lightweight project (4 hrs/wk) replacing the 6-hr backend project. Uses SQL & Python.',
      prerequisites: 'Python (Level 2), SQL (Level 1)',
      weeklyHours: 4,
      unlocks: 'Data Visualization (Level 3), Data Analysis (Level 2)',
      noteColor: 'yellow',
      isModified: true,
      originalTitle: 'Campus Backend API Project (6 hrs/wk — Too Heavy)',
    },
    {
      stepNumber: 3,
      title: 'Applied AI Workshop (Oct 15)',
      type: 'Event',
      whyFits: 'Short weekend workshop (4 hrs/wk equivalent). Hands-on TensorFlow practice.',
      prerequisites: 'Python (Level 2), ML (Level 1)',
      weeklyHours: 4,
      unlocks: 'TensorFlow (Level 3), Model Deployment (Level 2)',
      noteColor: 'pink',
    },
    {
      stepNumber: 4,
      title: 'NLP with Transformers Seminar (Nov 10)',
      type: 'Event',
      whyFits: 'Replaces the 8-hour/week research project with a targeted 3-hour seminar series.',
      prerequisites: 'Python (Level 2), ML (Level 2)',
      weeklyHours: 3,
      unlocks: 'Natural Language Processing (Level 3)',
      noteColor: 'mint',
      isModified: true,
      originalTitle: 'NLP for Indian Languages Research (8 hrs/wk — Deferred)',
    },
    {
      stepNumber: 5,
      title: 'Campus Chatbot Project',
      type: 'Project',
      whyFits: '5 hrs/week max commitment. Builds practical NLP chatbot for campus FAQ.',
      prerequisites: 'Python (Level 2), SQL (Level 1)',
      weeklyHours: 5,
      unlocks: 'NLP (Level 2), REST (Level 2)',
      noteColor: 'yellow',
    },
    {
      stepNumber: 6,
      title: 'TechCorp India AI Engineer Placement',
      type: 'Placement',
      whyFits: 'Same placement target reached under a lighter, steady 5-hour weekly pace!',
      prerequisites: 'Python (L3), ML (L3), TensorFlow (L2), NLP (L2)',
      weeklyHours: 0,
      unlocks: 'Full-time AI Engineer Job Offer (₹18 LPA)',
      noteColor: 'mint',
    },
  ],
};
